name: environments practice

on: 
  workflow_dispatch:

jobs:
  example_environments:
    runs-on: ubuntu-latest
    environment: "PROD"
    steps:
      - name: output
        run: |
          echo "${{ vars.HELLO_WORLD }}" >> $GITHUB_STEP_SUMMARY
