name: environments practice

on: 
  workflow_dispatch:
    inputs:
      環境:
        description: '環境を選択して下さい'
        required: true
        default: 'DEV'
        type: choice
        options:
          - PROD
          - STAGING
          - DEV

jobs:
  example_environments:
    runs-on: ubuntu-latest
    environment: "${{ inputs.ENVIRONMENT }}"
    steps:
      - name: output
        run: |
          echo "${{ vars.HELLO_WORLD }}" >> $GITHUB_STEP_SUMMARY
